### ISSUE TITLE
Print version number with `--version`

### ISSUE THREAD

**Issue by msooseth** [a16z/halmos#115]
**Is your feature request related to a problem? Please describe.**
I'd like to get the version of `halmos` so so when benchmarking using https://github.com/eth-sc-comp/benchmarks I can get the version programmatically. This would allow me to compare the performance of different `halmos` versions with ease

**Describe the solution you'd like**
A new option `--version` that prints the current version number. A git hash would also be nice, but not necessary.

**Describe alternatives you've considered**
I could get the version from nix I think. But it may be helpful to users to know their version number, too.

**Additional context**
I am trying to check the performance of different symbolic/concolic EVM execution engines.

**Comment by daejunpark** [comment]
Thank you for the suggestion! It was on our todo list, but we will prioritize it more now!

**Comment by daejunpark** [comment]
fixed by #117
