### ISSUE TITLE
Support for Foundry EVM cheatcodes

### ISSUE THREAD

**Issue by OxMarco** [a16z/halmos#17]
Does Halmos support Foundry EVM cheat codes?
Error: `unknown constant evm_div`

**Comment by daejunpark** [comment]
This might be a bug, should be a quick fix.

**Comment by daejunpark** [comment]
@OxMarco  Could you please provide an example to reproduce?  I cannot reproduce that error.

**Comment by daejunpark** [comment]
Thanks for reporting @OxMarco! It should be fixed in the latest version. Please feel free to reopen if not!

**Comment by OxMarco** [comment]
It doesn't show up anymore, if it does I will reopen the issue. Thanks!
