### ISSUE TITLE
External call encountered an issue at DELEGATECALL

### ISSUE THREAD

**Issue by banicg** [a16z/halmos#188]
**Issue Description**
I have a simple toy example which includes a _backdoor_ proof, and it works as expected. However, if I make this contract upgradeable using OpenZeppelin UUPSUpgradeable, I get the following warning after the backdoor prove fails: 
_WARNING:Halmos:CALL failed: External call encountered an issue at DELEGATECALL: External call encountered an issue at CALLDATALOAD: symbolic CALLDATALOAD offset: 4 + Extract(7935, 7680, halmos_data_bytes_02)_.

I attached 2 contracts: _SimpleContract_  would pass in all cases, but _SimpleContractUpgradeable_ will fail at `prove4_NoBackdoor`.

Each contract also have a commented-out method named `backdoor`, which should cause the _NoBackdoor_ prove to fail in both cases. For _SimpleContract_, it fails cleanly as expected with a counter example. For _SimpleContractUpgradeable_ it similarly fails with a counter example, but it also includes the same error as above. Hopefully this also give some perspective on the root cause.

**To Reproduce**
Attachements SimpleContract.sol and SimpleContractUpgradeable.sol (with txt file extensions)

**Environment:**
 - OS: Ubuntu 22.04 VM
 - Python version: Python 3.11.4
 - Halmos and other dependency versions: 
 Package                Version
---------------------- -------------
aiohttp                3.8.4
aiosignal              1.3.1
async-timeout          4.0.2
attrs                  23.1.0
bitarray               2.7.6
blinker                1.4
cbor2                  5.4.6
certifi                2023.5.7
charset-normalizer     3.1.0
command-not-found      0.3
cryptography           3.4.8
crytic-compile         0.3.2
cytoolz                0.12.1
dbus-python            1.2.18
distro                 1.7.0
distro-info            1.1build1
eth-abi                4.1.0
eth-account            0.9.0
eth-hash               0.5.2
eth-keyfile            0.6.1
eth-keys               0.4.0
eth-rlp                0.3.0
eth-typing             3.4.0
eth-utils              2.1.1
frozenlist             1.3.3
halmos                 0.1.2
hexbytes               0.3.1
httplib2               0.20.2
idna                   3.4
importlib-metadata     4.6.4
jeepney                0.7.1
jsonschema             4.17.3
keyring                23.5.0
launchpadlib           1.10.16
lazr.restfulclient     0.14.4
lazr.uri               1.0.6
lru-dict               1.2.0
more-itertools         8.10.0
multidict              6.0.4
netifaces              0.11.0
oauthlib               3.2.0
packaging              23.1
parsimonious           0.9.0
pip                    22.0.2
prettytable            3.8.0
protobuf               4.23.3
pycryptodome           3.18.0
PyGObject              3.42.1
PyJWT                  2.3.0
pyparsing              2.4.7
pyrsistent             0.19.3
python-apt             2.4.0+ubuntu1
PyYAML                 5.4.1
regex                  2023.6.3
requests               2.31.0
rlp                    3.0.0
SecretStorage          3.3.1
setuptools             59.6.0
six                    1.16.0
slither-analyzer       0.9.5
solc-select            1.0.4
systemd-python         234
toolz                  0.12.0
ubuntu-advantage-tools 8001
ufw                    0.36.1
unattended-upgrades    0.1
UNKNOWN                0.1.4
urllib3                2.0.3
wadllib                1.3.6
wcwidth                0.2.6
web3                   6.5.0
websockets             11.0.3
wheel                  0.37.1
yarl                   1.9.2
z3-solver              4.12.2.0
zipp                   1.0.0

**Additional context**
The *.sol files uses Hardhat import references.
[SimpleContract.t.sol.txt](https://github.com/a16z/halmos/files/12404173/SimpleContract.t.sol.txt)
[SimpleContractUpgradeable.t.sol.txt](https://github.com/a16z/halmos/files/12404175/SimpleContractUpgradeable.t.sol.txt)

**Comment by daejunpark** [comment]
Thanks for the repro!

This is a known limitation. Please refer to this wiki page:
https://github.com/a16z/halmos/wiki/errors#symbolic-calldataload-offset

In your case, the arguments for `UUPSUpgradeable.upgradeToAndCall(address,bytes)` need to be explicitly constructed as described in the wiki page.

Please let me know if you have any further questions!

**Comment by banicg** [comment]
Thanks, it is working perfectly now!

**Comment by karmacoma-eth** [comment]
The error message has been documented here for future reference: https://github.com/a16z/halmos/wiki/errors#symbolic-calldataload-offset
