### ISSUE TITLE
vm.getBlockNumber not supported

### ISSUE THREAD

**Issue by 0xllill** [a16z/halmos#270]
**Describe the bug**
When using vm cheatcode from foundry we get the error : `WARNING:Halmos:Encountered Unsupported cheat code: calldata = 0x42cbb15c` 
Can be bypass using block.number directly on the code but could be a nice addition to Halmos

**To Reproduce**
Use vm.getBlockNumber() in your test file

**Environment:**
 - OS: macOs
 - Python version: 3.12.2
 - Halmos and other dependency versions: halmos 0.1.11

**Additional context**
cheatcode not supported

**Comment by karmacoma-eth** [comment]
TIL, this was added [4 months ago](https://github.com/foundry-rs/forge-std/commit/87a2a0afc5fafd6297538a45a52ac19e71a84562)

```solidity
    /// Gets the current `block.number`.
    /// You should use this instead of `block.number` if you use `vm.roll`, as `block.number` is assumed to be constant across a transaction,
    /// and as a result will get optimized out by the compiler.
    /// See https://github.com/foundry-rs/foundry/issues/6180
    function getBlockNumber() external view returns (uint256 height);
```
