### ISSUE TITLE
Remove `metadata` checks for files with free functions / file-level functions

### ISSUE THREAD

**Issue by pcaversaccio** [a16z/halmos#281]
**Describe the bug**

If you currently use in some form contracts that use [free functions](https://soliditylang.org/blog/2020/09/02/solidity-0.7.1-release-announcement/) (a.k.a file-level functions) via imports, `halmos` will issue the following warning:

```sh
Skipped FreeFunctionsFile.json due to parsing failure: KeyError: 'metadata'
```

Currently, this warning is printed in red colour. I would suggest orange should be enough ;). The underlying reason is that these files are compiled in the normal way (since in some contracts you will use them) but there is no `metadata` available in the standard JSON input file for these files.

**To Reproduce**

`git` clone `https://github.com/pcaversaccio/snekmate` and checkout the `feat/halmos` branch. Run `pnpm install` and `forge install` and invoke:

```sh
halmos --contract ERC20TestHalmos --function testHalmosAssertNoBackdoor --storage-layout generic --ffi -vvvv
```

![image](https://github.com/a16z/halmos/assets/25297591/8aba1ebc-ffdc-4203-a7e6-4b26cefc22de)

**Environment:**
 - OS: `Linux`
 - Python version: `3.11.3`
 - Halmos and other dependency versions: `0.1.13.dev1+ga617814`

**Comment by karmacoma-eth** [comment]
Trying to get to the bottom of this issue:

using forge 0.2.0 (9444c62 2024-07-26T00:22:04.784959000Z) and solc 0.8.26 (so both up to date), halmos invokes `forge build` with the `--extra-output metadata` flag. 

We use this to parse the compiler version in each `out/<filename>.sol/<contract_or_filename>.json`.

However, when a solidity does not contain a contract body, it seems that the `metadata` section of the json output is missing. Some examples where this can happen:

console2.sol, just an import:

```
// SPDX-License-Identifier: MIT
pragma solidity >=0.4.22 <0.9.0;

import {console as console2} from "./console.sol";
```

Just a sol file with no code at all:

```
// SPDX-License-Identifier: MIT
pragma solidity >=0.4.22 <0.9.0;
```

A sol file with free functions (like https://github.com/transmissions11/solmate/blob/main/src/utils/SignedWadMath.sol):

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

function inc(uint256 x) pure returns (uint256) {
    return x + 1;
}
```

A sol file containing struct definitions only: https://github.com/code-423n4/2024-06-size/blob/main/src/SizeViewData.sol

A json file is still produced for these, which includes the AST, but it has no metadata section, for instance:

```
{
  "abi": [],
  "bytecode": {
    "object": "0x",
    "linkReferences": {}
  },
  "deployedBytecode": {
    "object": "0x",
    "linkReferences": {}
  },
  "ast": { ... },
  "id": 26
}
```

We can rule out a forge issue, I think this demonstrates that this can be directly reproduced with solc:

```sh
❯ solc src/LibraryWithCode.sol --metadata --pretty-json                                                                                                                                                                                     

======= src/LibraryWithCode.sol:Incrementer =======
Metadata:
{"compiler":{"version":"0.8.26+commit.8a97fa7a"},"language":"Solidity","output":{"abi":[{"inputs":[{"internalType":"uint256","name":"number","type":"uint256"}],"name":"increment","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"pure","type":"function"}],"devdoc":{"kind":"dev","methods":{},"version":1},"userdoc":{"kind":"user","methods":{},"version":1}},"settings":{"compilationTarget":{"src/LibraryWithCode.sol":"Incrementer"},"evmVersion":"cancun","libraries":{},"metadata":{"bytecodeHash":"ipfs"},"optimizer":{"enabled":false,"runs":200},"remappings":[]},"sources":{"src/LibraryWithCode.sol":{"keccak256":"0x7849820748231a57500d0e5e899a900d7f4562ca743a11d352e728e14224eb49","license":"MIT","urls":["bzz-raw://0c65523012373b73c957570390187c2223538d242f7a75456e91057149546287","dweb:/ipfs/QmdMequXv7xNaVQ5QbHbCttggoJ8DEx7RGqwPiLGuwYqBX"]}},"version":1}

❯ solc src/FreeFuncs.sol --metadata --pretty-json                                                                                                                                                                                     
Compiler run successful. No contracts to compile.
```

It would be nice if solc consistently emitted metadata, but it seems like we won't be able to rely on that in the foreseeable future, so we need to find a way to deal with it on our side.

**Comment by karmacoma-eth** [comment]
I propose to go the other way around:
- instead of checking for the compiler version first (and erroring out early), we look for a contract definition first
- if there is no contract definition, we know there is no test, and it's safe to skip
- if there is a contract definition, but no compiler version, then we have a problem and we can warn about it
