### ISSUE TITLE
Create a halmos Docker image with multiple solvers preinstalled

### ISSUE THREAD

**Issue by karmacoma-eth** [a16z/halmos#282]
Description TBD

**Comment by daejunpark** [comment]
list of solvers:
- bitwuzla: https://bitwuzla.github.io/
- yices: https://yices.csl.sri.com/
- boolector: https://github.com/Boolector/boolector
- cvc4: https://cvc4.github.io/
- cvc5: https://cvc5.github.io/
- stp: https://stp.github.io/

**Comment by karmacoma-eth** [comment]
in https://github.com/a16z/halmos/pull/302
