### ISSUE TITLE
Unsupported cheatcode error

### ISSUE THREAD

**Issue by nican0r** [a16z/halmos#321]
**Describe the bug**
I’m working on adding halmos to this existing foundry repo: https://github.com/Recon-Fuzz/create-chimera-app/tree/halmos 

But when I try to use the `eq` assertion provided by the [chimera framework](https://github.com/Recon-Fuzz/chimera) I get an unsupported cheatcode error even though when I trace through the definition of `eq` there are no cheatcodes used. 

I know I could just use a standard solidity assertion instead but would really like to use the one from chimera because the repo’s meant to be a demonstration of it and would like to clarify if this is an issue in my implementation or a bug. 

![Pasted Graphic](https://github.com/a16z/halmos/assets/94120714/e5f0a60a-2436-4455-b7cb-4c1dbf297b9b)

Implementation:
![image](https://github.com/a16z/halmos/assets/94120714/599b7d55-55b9-4e5d-aa0e-e2136748badb)

[HalmosAsserts::eq](https://github.com/Recon-Fuzz/chimera/blob/d5cf52bc5bbf75f988f8aada23fd12d0bcf7798a/src/HalmosAsserts.sol#L24-L26)
![image](https://github.com/a16z/halmos/assets/94120714/5418dcca-43e2-4243-ac66-21458b1b20c4)

The above inherits from forge-std/test.sol:
![image](https://github.com/a16z/halmos/assets/94120714/4d2b73e1-d905-44ba-ab05-e4439c0e8dcb)

**To Reproduce**
Use the following repo: https://github.com/Recon-Fuzz/create-chimera-app/tree/halmos  
Run: `halmos --mc HalmosTester ` from root

**Environment:**
 - OS:  macOS Sonoma 14.5
 - Python version: Python 3.10.10

**Comment by daejunpark** [comment]
we're working on this in #323

**Comment by karmacoma-eth** [comment]
should be fixed now that #323 is merged and should be available in the soon-to-be-released halmos v0.1.14
