### ISSUE TITLE
Unable to install halmos on macOs ventura 13.0.1

### ISSUE THREAD

**Issue by viraj124** [a16z/halmos#35]
I installed halmos with `pip3  install halmos` but on running halmos I get `zsh command not found` I checked my path in zrsh file and it is correct is there something that i am missing ?

Thanks

**Comment by shanzson** [comment]
Hi can you tell how did you fix it?

**Comment by shanzson** [comment]
Okay, got it. The executable file for here: /Users/username/Library/Python/3.9/bin
