### ISSUE TITLE
Getting the path count before solving

### ISSUE THREAD

**Issue by jrstrunk** [a16z/halmos#430]
Hello, is there a way to get the number of paths that will be solved at the beginning of the run? It would be nice to see if I just started a giant process before waiting for it to time out.

**Comment by jrstrunk** [comment]
Answered on telegram, thanks!

**Comment by daejunpark** [comment]
There are two phases in halmos, and the number of paths to solve is available after the first phase. You can see it in the progress display: "solving queries: SOLVED / TOTAL", which is a new feature added in the latest release: https://github.com/a16z/halmos/pull/417

**Comment by jrstrunk** [comment]
Oh that is neat, thanks for the info! I'll make sure I am on the newest version
