### ISSUE TITLE
Struct type parameters not supported

### ISSUE THREAD

**Issue by acmLL** [a16z/halmos#55]
Applied halmos on the attached (flat version) project and got this error message

Running 4 tests for contracts/test/TestCurveSwapper.sol:TestCurveSwapper
Traceback (most recent call last):
  File "/usr/local/bin/halmos", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/halmos/__main__.py", line 478, in main
    exitcode = run(setup_ex, abi, funname, funsig, funselector, arrlen, args, options)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/halmos/__main__.py", line 171, in run
    raise ValueError('Not supported', param_type) # TODO: support struct types
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: ('Not supported', 'tuple')

Thanks!!!

[TestCurveSwapper_FlatVersion.sol.zip](https://github.com/a16z/halmos/files/11224227/TestCurveSwapper_FlatVersion.sol.zip)

**Comment by daejunpark** [comment]
Test function parameters of struct type are currently not supported, but will be added in the near future.
